### ISSUE TITLE
[ iEEG_Atlas use case ] Multiple sites per user

### ISSUE THREAD

**Issue by christinerogers** [neurohub/neurohub_asana#110]
Existing NeuroHub/CBRAIN users can't be affiliated to more than one site. 

For example, the _christine_ NeuroHub credential is attached to site: _acelab_. 
To access the _iEEG_Atlas_ site on NeuroHub, I currently use a separate credential. 

This is an inconvenience but not a show-stopper. The current workaround is using a shared project credential and/or creating additional site-specific user credentials. 
(This is based on my current understanding from Pierre.)
Possibly related to: #103 #97

**Comment by prioux** [comment]
Sites don't exist in NeuroHub at all. On the CBRAIN side, the model is user is only a member of one site. We're not going to change that. Shared workgroups are the way to allow a user to access multiple resources.
