### ISSUE TITLE
[ iEEG_Atlas use case ] Multiple users per SFTP-1 space 

### ISSUE THREAD

**Issue by christinerogers** [neurohub/neurohub_asana#111]
To enabledata-upload via NeuroHub for the iEEG_Atlas project --
A single user credential (_ieeg_atlas_loris_) is currently shared on SFTP-1 by:
* all clinical sites transferring (uploading) data for the project
* the LORIS server's back-end script which copies (receives) data from this user directory on SFTP-1 

If a future SFTP setup could enable different user credentials to use the same directory, that would be ideal. 
Different privilege levels would be a bonus to prevent against data loss and errors, e.g clinical sites should not be able to delete files from the shared upload space. 
related to: #110

**Comment by prioux** [comment]
How it should be is for the iEEG_Atlas project to use one user per site, that's the only real way to go.
