### ISSUE TITLE
Put Bittorrent Git Annex Notes on NEUROHUB! Github

### ISSUE THREAD

**Issue by dlq** [neurohub/neurohub_asana#22]
Put Bittorrent Git-Annex notes . on Github

**Comment by dlq** [comment]
➤ Emmet A. O&#39;Brien commented:

First draft of this is now in place at https://github.com/neurohub/neurohub_documentation/torrent_notes.md

**Comment by xlecours** [comment]
I have tested the procedure to add torrent data to github and it worked flawlessly. https://github.com/neurohub/neurohub_documentation/blob/master/torrent_notes.md
