### ISSUE TITLE
Customize Front-End for NeuroHub

### ISSUE THREAD

**Issue by dlq** [neurohub/neurohub_asana#55]
https://docs.google.com/document/d/1z5P0P2MMTH0W0iQEkRYfm31LBf88Zzl_0vilCp9UVlI/edit#

**Comment by dlq** [comment]
➤ serge.boroday commented:

Hi, @Liam 'facelift' might need change the ember-osf-web or in some cases osf.io . I started renameing osf to neurohub at https://github.com/sergiy-neurohub/ember-osf-web but did not try test or run it. The Vagrant file for the backend  developemnt environment is at 
https://github.com/MontrealSergiy/osf-Vagrant (to be adapted to the official neurohub fork repos). see also neurohub.ca for logo and basic info

**Comment by liam** [comment]
Wrong Liam
Please read
https://github.blog/2011-03-23-mention-somebody-they-re-notified/

**Comment by dlq** [comment]
➤ Diana Le commented:

Decision on if moving forward with OSF or creating from scratch.
