### ISSUE TITLE
Metadata Extraction API

### ISSUE THREAD

**Issue by dlq** [neurohub/neurohub_asana#69]

**Comment by dlq** [comment]
➤ Diana Le commented:

Emmet: Currently laying the foundations

**Comment by dlq** [comment]
➤ Emmet A. O&#39;Brien commented:

We should clarify exactly what functionaiity is wanted and falls under this heading.

**Comment by xlecours** [comment]
This is unclear. 
Metadata; which one and about what?
Extraction API; new CBRAIN API endpoints? let's define them as needed.
Closing
