### ISSUE TITLE
DATA SPACE - MVP Checklist

### ISSUE THREAD

**Issue by dlq** [neurohub/neurohub_asana#84]
- [ ] Create a ukbiobank project

**Comment by xlecours** [comment]
Updating this issue description to reflect the current status.
- **Search datasets (research-objects) available** will be achieved by searching in the dashboard for NeuroHub content (project and files) (see https://github.com/neurohub/neurohub-asana/issues/108)
- **Add, link or bookmark items from the dataspace to a project, in the project space** this is done by the invitation process (a collaborator can see and search a project content) and with public project which every NeuroHub user can see the content of.
