### ISSUE TITLE
Adding collaborators functionality 

### ISSUE THREAD

**Issue by dlq** [neurohub/neurohub_asana#97]
_MVP Feature tracking issue._ 

- [x] A user can add collaborators to her own projects. 

Process steps:
1. From the project space, collaborators can be invited by clicking on the "invite other user" button. 
2. The system, ask for an email address to send the invitation to. 
3. An email is sent to the invitee notifying that user that an invitation is pending. 
4. Upon next login, a banner in the dashboard ask the user to accept, decline or "snooze" the invitation. 
5. Once accepted, the user will have view only permission on the project. The owner of the project can grant additional permission (edit) to the invitee.

**Comment by dlq** [comment]
➤ Xavier Lecours commented:

This is already an existing feature of CBRAIN. It is missing the GUI part of it so a wab page need to be created for that. Additionally, the collaborators can only view the projects, not edit it.
I am creating sub tasks for this.

**Comment by xlecours** [comment]
Updating description to describe the process.
